apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudops-backend
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudops-backend-role
  namespace: default

rules:
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudops-backend-rolebinding
  namespace: default

subjects:
  - kind: ServiceAccount
    name: cloudops-backend
    namespace: default

roleRef:
  kind: Role
  name: cloudops-backend-role
  apiGroup: rbac.authorization.k8s.io